# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15f0f2a5920aefa0a4d27c0d2b73e188699b99d5e5e1dc2faa22ad66e4f83cce03594ebf15945b957650ee159d063d9faed5dd83da2b471618f8193f43ff004b

test:
  secret_key_base: 753506304eea4bea0e319c5bb192696d8ed557a249111f2fdd26c0a4419cb02f6b37c4cd461ae235470e3e05584a41e7dc9e28f269174b5f3da9bdc0d1868b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
